fix: Making sure all Sentry processing runs in the collaborative background thread pool.
Infomaniak/ios-kDrive pull request #1064
Opened 2023-11-17 16:36 UTC by adrien-coye

2023-11-20 06:50 UTC, PhilippeWeidmann requested changes
Only applying Task doesn't switch threads. We will discuss it live.

2023-11-21 08:51 UTC, adrien-coye commented
@PhilippeWeidmann Using `Task` does … depending on the actor context. Here it does work as I'm outside the main actor as we did discuss yesteday.

I did use the `Task.detached` to leave the main actor, when needed, but I will refactor aroud it to not use it anymore for my code to be cleaner. I'll prepare a proper set of slide for next monday to sort this out for the team for good 👍

2023-11-21 08:52 UTC, adrien-coye commented on kDrive/UI/Controller/Menu/ParameterTableViewController.swift
> +        Task.detached {
TODO: refactor

2023-11-21 17:54 UTC, adrien-coye commented on kDriveCore/Data/Api/DriveApiFetcher.swift
> +            Task {
TODO use SentryDebug

2023-11-22 14:52 UTC, adrien-coye commented on kDriveCore/Data/Api/DriveApiFetcher.swift
> +                    let breadcrumbMetadata = (credential as ApiToken).breadcrumbMetadata()
TODO: remove

2023-11-22 15:03 UTC, adrien-coye commented on kDriveCore/Utils/KeychainHelper.swift
> +                    let metadata = token.breadcrumbMetadata()
missing `resultCode`

2023-11-22 15:25 UTC, merged