feat: Multiselect behaviour
Infomaniak/ios-kDrive pull request #1311
Opened 2024-09-27 13:17 UTC by adrien-coye

- [ ] Multi select
- [ ] Multi select actions

2024-10-30 09:32 UTC, adrien-coye reviewed
Self assesment

2024-10-30 09:32 UTC, adrien-coye commented on kDrive/AppRouter.swift
> +            // TODO: i18n
TODO i18n

2024-10-30 09:32 UTC, adrien-coye commented on kDrive/UI/Controller/Files/FilePresenter.swift
> +            // TODO: i18n
TODO: i18n

2024-11-27 06:26 UTC, adrien-coye commented on kDriveCore/Data/DownloadQueue/DownloadArchiveOperation.swift
> +        // TODO: missing imp
TODO

2024-11-27 08:07 UTC, adrien-coye commented on kDrive/UI/Controller/Files/MultipleSelectionFloatingPanelViewController.swift
> +    // TODO: make it work
TODO: Archive KO with public share

2024-12-06 14:12 UTC, PhilippeWeidmann reviewed
Even if viewControllerDismissable is a protcol and is weak. I don't think it is a good practice to keep a reference to the ViewController from the ViewModel.

The VM shouldn't control the ViewController. However you indeed need to callback your VC if you want to dismiss it.
In the code base I see two examples: 
- Implement the logic inside the VC (see SearchViewController)
- Using a callback. It's more work but maybe more appropriate

2024-12-06 14:22 UTC, adrien-coye commented
@PhilippeWeidmann Yeah I agree, I felt it was not perfect while doing it. Yeah I can use a callback there.

2024-12-19 12:04 UTC, PhilippeWeidmann requested changes
The DownloadQueue can handle different operations . 
We already have `DownloadOperation` and `DownloadArchiveOperation` maybe you could subclass `DownloadArchiveOperation` with `DownloadPublicShareArchiveOperation` it passing `shareDrive` and `publicShareProxy` when you don't need it. 

Also I think I missed it in an other review, but the same thing can be done for single files in `DownloadOperation` but the refactor should be done in a separate PR.

2024-12-19 12:05 UTC, PhilippeWeidmann commented on kDrive/UI/Controller/Files/File List/MultipleSelectionFileListViewModel.swift
> +        id: MultipleSelectionActionId.move,
Same for the other ones
```suggestion
        id: .move,
```

2024-12-19 12:07 UTC, PhilippeWeidmann commented on kDrive/UI/Controller/Files/File List/FileListViewModel.swift
> +    var dismissClosure: (() -> Void)?
There is already a naming pattern and a "region" to declare callbacks, see:
https://github.com/Infomaniak/ios-kDrive/blob/c35026c147d0c9811d2cde3990fbd55ab13a156d/kDrive/UI/Controller/Files/File%20List/FileListViewModel.swift#L136

2025-01-07 08:44 UTC, adrien-coye commented on kDriveCore/Data/DownloadQueue/DownloadQueue.swift
> +    public func operation(for fileId: Int) -> DownloadAuthenticatedOperation? {
Should be the abstract `DownloadOperation` now

2025-01-07 08:58 UTC, adrien-coye commented on kDriveCore/Data/DownloadQueue/DownloadQueue.swift
> +    public func operation(for fileId: Int) -> DownloadAuthenticatedOperation? {
Yes I can since last refactor. Using `DownloadFileOperationable` now.

2025-01-07 09:26 UTC, PhilippeWeidmann approved these changes

2025-01-07 09:27 UTC, merged