feat: Public share locked and expired UI
Infomaniak/ios-kDrive pull request #1328
Opened 2024-10-23 07:32 UTC by adrien-coye

- [x] Network stack error parsing
- [x] Public share UI
- [x] Expired UI
- [x] i18n

Feature branch https://github.com/Infomaniak/ios-kDrive/pull/1306

![IMG_3394](https://github.com/user-attachments/assets/f9f60f58-7998-4759-8804-2713fa29ba38)
![IMG_3393](https://github.com/user-attachments/assets/865bacff-de14-4838-8002-4680f0a2148f)

2024-10-30 07:08 UTC, adrien-coye reviewed
I did a self review and left notes for the sake of the next reviewer.

2024-10-30 07:08 UTC, adrien-coye commented on kDrive/AppDelegate.swift
> +            let somePublicShare = URL(string: "https://kdrive.infomaniak.com/app/share/140946/81de098a-3156-4ae6-93df-be7f9ae78ddd")
We can merge this to the host PR, it does not matter yet. The last PR will do the cleanup.

2024-10-30 07:08 UTC, adrien-coye commented on kDrive/AppRouter.swift
> +        guard let window,
The routing will change on the last PR to work offline too.

2024-10-30 07:08 UTC, adrien-coye commented on kDrive/AppRouter.swift
> +        guard let window,
The routing will change on the last PR to work offline too.

2024-10-30 07:08 UTC, adrien-coye commented on kDrive/UI/Controller/Files/External/BaseInfoViewController.swift
> +class BaseInfoViewController: UIViewController {
Pure autolayout code view, not added comments to match what is expected.

2024-10-30 07:08 UTC, adrien-coye commented on kDrive/UI/Controller/Files/External/LockedFolderViewController.swift
> +class LockedFolderViewController: BaseInfoViewController {
Pure autolayout code view, not added comments to match what is expected.

2024-10-30 07:47 UTC, adrien-coye reviewed
To change

2024-10-30 07:47 UTC, adrien-coye commented on kDrive/UI/Controller/Files/External/UnavaillableFolderViewController.swift
> +        titleLabel.text = KDriveStrings.Localizable.dropboxPublicShareOutdatedTitle
public share key

2024-10-30 07:47 UTC, adrien-coye commented on kDrive/UI/Controller/Files/External/UnavaillableFolderViewController.swift
> +        descriptionLabel.text = KDriveStrings.Localizable.dropboxPublicShareOutdatedDescription
also public share key

2024-11-01 14:16 UTC, PhilippeWeidmann commented on kDriveCore/Utils/Logging.swift
This shouldn't be committed

2024-11-01 14:26 UTC, PhilippeWeidmann requested changes
Some general UI remarks:
- [x] Use IKLabel with the correct style instead of .preferredFont & co
- [x] If possible use embed this VC inside a UINavigationViewController to get the native close Button inside the navigationBar
- [x] Spacing is incorrect compared to the figma

(As I wont be there to approve, feel free to remove my request changes after it's done)

2024-11-11 11:40 UTC, adrien-coye commented on kDrive/UI/Controller/Files/External/BaseInfoViewController.swift
> +                         views: views)
Debatable, and you're not here.

2024-11-11 14:38 UTC, PhilippeWeidmann commented on kDrive/UI/Controller/Files/External/BaseInfoViewController.swift
> +                         views: views)
The issue with visual constraints is that it's not safe at all. I understand that it "reads" easier but for example if we change the name of centerImage the code will compile fine but it won't work anymore.

From the the top of my head, something like this should work:
```swift
centerImageView.topAnchor.constraint(equalTo: view.topAnchor)
titleLabel.topAnchor.constraint(equalTo: centerImageView.bottomAnchor)
descriptionLabel.topAnchor.constraint(equalTo: titleLabel.bottomAnchor)
descriptionLabel.bottomAnchor.constraint(equalTo: view.bottomAnchor)
```

It is indeed more verbose but it is safe at compile time.

2024-11-14 20:08 UTC, PhilippeWeidmann reviewed
Can't test it but I'm fine with merging if everything was addressed.

2024-11-14 20:08 UTC, PhilippeWeidmann approved these changes

2024-11-19 07:17 UTC, merged