Fix back button
Infomaniak/ios-kDrive pull request #567
Opened 2022-01-27 09:29 UTC by valentinperignon

2022-01-28 09:06 UTC, PhilippeWeidmann commented on kDrive/Utils/UINavigationItem+Extension.swift
> +    func dontShowBackButtonText() {
Rename "dontShow" to "hide":
- It improves code readability 
- It looks more like Apple's own style (eg. view.isHidden)

2022-01-28 09:06 UTC, PhilippeWeidmann requested changes
Rename "dontShow" to "hide":

It improves code readability
It looks more like Apple's own style (eg. view.isHidden)

2022-01-31 08:46 UTC, PhilippeWeidmann submitted a review, later dismissed

2022-01-31 10:05 UTC, flowbe approved these changes

2022-01-31 10:39 UTC, Lnamw approved these changes

2022-01-31 10:39 UTC, merged